### ISSUE TITLE
mobile skins support

### ISSUE THREAD

**Issue by bikb** [mike-kfed/rcmail-thunderbird-labels#30]
Hello,

thank you for this great plugin.
I have bought a skin from roundcubeskin.com. It is not compatible to this plugin out of the box.

But you only have to change the folder name "larry" in plugins/thunderbird_labels/skins/ to the actual skin for example "silver". So it works. :o)

Best regards

**Comment by mike-kfed** [comment]
Thanks for the hint, I added that information to the readme!
