### ISSUE TITLE
Plugin incompatible with RC 1.3.x

### ISSUE THREAD

**Issue by filhocf** [mike-kfed/rcmail-thunderbird-labels#31]
Updating my docker image with RC 1.3.beta and tbird-labes, got a env with problems, with tbird-labels inactive. Follow the screenshot:

![image](https://cloud.githubusercontent.com/assets/952596/22432396/e8f57252-e6fb-11e6-9722-613bf528ca5c.png)

**Comment by mike-kfed** [comment]
I just tried current master and my arbitrary_labels branch, works for me with roundcube 1.3-beta. you seem to be using a theme other than classic or larry, maybe you need to rename the `plugins/thunderbird_labels/skins/larry` folder to the name of your skin?

Any errors showing in the javascript console? they might help you find the problem aswell.

**Comment by filhocf** [comment]
I rebuilded my docker env and yes, was my fault. It is ok. Thanks by your attention and sorry by my mistake.
